<?xml version="1.0" ?>
<!DOCTYPE mylist [
<!ELEMENT mylist (contact+)>
  <!ELEMENT contact (name, email)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
]>
<mylist>
  <contact>
	<name>Peter Ohring</name>
        <email>peter.ohring@purchase.edu</email>
  </contact>
  <contact>
	<name>Joel Tenenbaum</name>
        <email>joel@purvid.ns.purchase.edu</email>
  </contact>
  <contact>
	<name>Marty Lewinter</name>
        <email>mathman@purchase.edu</email>
  </contact>
  <contact>
	<name>Jeanine Meyer</name>
        <email>jeanine.meyer@purchase.edu</email>
  </contact>
</mylist>
