<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shows [
<!ELEMENT shows (show+)>
  <!ELEMENT show (show_title, score)>
    <!ELEMENT show_title (#PCDATA)>
    <!ELEMENT score (#PCDATA)>
]>
<shows>
  <show>
    <show_title>The Sopranos</show_title>
    <score>0</score>
  </show>
  <show>
    <show_title>NYPD</show_title>
    <score>0</score>
  </show>
  <show>
    <show_title>Law and Order</show_title>
    <score>0</score>
  </show>
  <show>
    <show_title>Judging Amy</show_title>
    <score>0</score>
  </show>
  <show>
    <show_title>The News Hour</show_title>
    <score>0</score>
  </show>
</shows>
