=== zhaoyiyi/semester2/5203XML/week2/song.dtd
<!ELEMENT SONG (TITLE, COMPOSER+, PRODUCER*, PUBLISHER*, LENGTH?, YEAR?, ARTIST+)>
  <!ELEMENT TITLE (#PCDATA)>
  <!ELEMENT COMPOSER (#PCDATA)>
  <!ELEMENT PRODUCER (#PCDATA)>
  <!ELEMENT PUBLISHER (#PCDATA)>
  <!ELEMENT LENGTH (#PCDATA)>
  <!ELEMENT YEAR (#PCDATA)>
  <!ELEMENT ARTIST (#PCDATA)>
  <!ATTLIST SONG id CDATA #IMPLIED>

=== zhaoyiyi/semester2/5203XML/week2/song.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SONG SYSTEM "song.dtd">
<SONG id="2">
  <TITLE>ADSFS</TITLE>
  <COMPOSER>adf</COMPOSER>
  <PRODUCER>asdf</PRODUCER>
  <PUBLISHER>asdf</PUBLISHER>
  <LENGTH>asdf</LENGTH>
  <YEAR>asdf</YEAR>
  <ARTIST>adf</ARTIST>
</SONG>
